[workspace]
members = [
    "components/clarinet-cli",
    "components/clarinet-deployments",
    "components/clarinet-files",
    "components/clarinet-utils",
    "components/clarity-fmt",
    "components/clarity-lsp",
    "components/clarity-jupyter-kernel",
    "components/stacks-rpc-client",
    "components/stacks-devnet-js",
    "components/stacks-network",
    "components/chainhook-types-rs",
    "components/chainhook-event-observer",
    "components/chainhook-node",
    "components/hiro-system-kit",
]
default-members = ["components/clarinet-cli", "components/chainhook-event-observer"]
