[project]
name = "counter"
authors = []
description = ""
telemetry = false

[contracts.counter]
path = "contracts/counter.clar"
clarity_version = 1
epoch = "2.05"

[contracts.counter-2]
path = "contracts/counter-v2.clar"
clarity_version = 2
epoch = "2.1"

[repl.analysis]
passes = ["check_checker"]
check_checker = { trusted_sender = false, trusted_caller = false, callee_filter = false }
